### ISSUE TITLE
symbol lookup error: /usr/lib64/libslapt.so.0: undefined symbol: EVP_MD_CTX_init

### ISSUE THREAD

**Issue by jomoga** [jaos/slapt-get#12]
slapt-get: symbol lookup error: /usr/lib64/libslapt.so.0: undefined symbol: EVP_MD_CTX_init

# slapt-get --version
slapt-get version 0.11.5

**Comment by jaos** [comment]
What Slackware release?

**Comment by jomoga** [comment]
slackware64-current as of 01/29/22.

It's defined in the openssl-1.1.1m package:

./include/openssl/evp.h:# define EVP_MD_CTX_init(ctx)    EVP_MD_CTX_reset((ctx))

I see that it's been depreciated: void EVP_MD_CTX_init (EVP_MD_CTX *ctx) HC_DEPRECATED

**Comment by jomoga** [comment]
Yes.  It's a snapshot build.

This is the libssl library in the 15.0 release:

# nm -D lib64/libssl.so.1.1 | grep EVP_MD
                 U EVP_MD_CTX_copy@OPENSSL_1_1_0
                 U EVP_MD_CTX_copy_ex@OPENSSL_1_1_0
                 U EVP_MD_CTX_ctrl@OPENSSL_1_1_0
                 U EVP_MD_CTX_free@OPENSSL_1_1_0
                 U EVP_MD_CTX_md@OPENSSL_1_1_0
                 U EVP_MD_CTX_new@OPENSSL_1_1_0
                 U EVP_MD_CTX_set_flags@OPENSSL_1_1_0
                 U EVP_MD_size@OPENSSL_1_1_0
                 U EVP_MD_type@OPENSSL_1_1_0

**Comment by jaos** [comment]
You may want to rebuild then, unless I'm missing something. The included slackbuild would be the preferred way to go.

**Comment by jomoga** [comment]
Ok, thanks.

**Comment by jomoga** [comment]
I cloned the code:

git clone https://github.com/jaos/slapt-get.git

Compiled and installed it.  Runs fine now.  Thanks again.
