### ISSUE TITLE
Add the ability to force install

### ISSUE THREAD

**Issue by babam86** [jaos/slapt-get#15]
Add the ability to force install if one of the dependencies is included in "EXCLUDE" (slapt-getrc)

For example, A depends on B and C, but B is included in "EXCLUDE" (slapt-getrc)

If slapt-get has the ability to force install then A and C can be installed

Thanks.

**Comment by jaos** [comment]
You can ignore those entries with `--ignore-excludes` when installing.

**Comment by babam86** [comment]
No, with --ignore-excludes the packages in "EXCLUDE" will be installed, that's not what I want.

**Comment by jaos** [comment]
When you specifically `--install A --ignore-excludes` it will pull in your ignored B along with C, etc.

**Comment by jaos** [comment]
You can use `--ignore-excludes --simulate` and grab the deps you want and then install them with `--no-dep`:

```sh
root@matisse # slapt-get --install xfce4-panel
Reading Package Lists...Done
Excluding xfce4-panel, use --ignore-dep to override
xfconf, which is required by xfce4-panel, is excluded
The following packages have been EXCLUDED:
  xfce4-panel 
0 upgraded, 0 reinstalled, 0 newly installed, 0 to remove, 1 not upgraded.

root@matisse # slapt-get --install xfce4-panel --ignore-exclude --simulate
Reading Package Lists...Done
The following NEW packages will be installed:
  exo garcon libICE libSM libXres libdbusmenu libwnck3 libxfce4ui libxfce4util 
  startup-notification xcb-util xfconf xfce4-panel 
0 upgraded, 0 reinstalled, 13 newly installed, 0 to remove, 0 not upgraded.
Need to get 2.6MB of archives.
After unpacking 18.8MB of additional disk space will be used.
...
```
Then install
```
slapt-get --no-dep --install  exo garcon libICE libSM libXres libdbusmenu libwnck3 libxfce4ui libxfce4util startup-notification xcb-util xfce4-panel
```
