### ISSUE TITLE
WORKINGDIR variable

### ISSUE THREAD

**Issue by babam86** [jaos/slapt-get#16]
Is it possible to add "WORKINGDIR" variable, so no need to edit slapt-getrc.

For example, 
WORKINGDIR=/mnt/sda2/slapt-get slapt-get --install gimp
WORKINGDIR=/tmp/packages slapt-get --download-only --install imagemagick

Thanks.

**Comment by jaos** [comment]
No but you can have custom configuration files with the `--config` option that can point wherever you want.

**Comment by babam86** [comment]
Is there a plan to support it.

**Comment by jaos** [comment]
No, there is not plan to add checking the environment for every configuration option in addition to the configuration file itself.

You can make a wrapper pretty simply:

```
function slapt-get-customworkdir() {
    WORKINGDIR=${WORKINGDIR:-/tmp/workingdir.$$}
    mkdir -p "${WORKINGDIR}"
    sed -re "s,^(WORKINGDIR=).*,\1${WORKINGDIR},g" /etc/slapt-get/slapt-getrc > "${WORKINGDIR}/slapt-getrc"
    slapt-get --config "$WORKINGDIR/slapt-getrc" $@
}
```

**Comment by babam86** [comment]
Thank you very much.

**Comment by babam86** [comment]
> No, there is not plan to add checking the environment for every configuration option in addition to the configuration file itself.
> 
> You can make a wrapper pretty simply:
> 
> ```
> function slapt-get-customworkdir() {
>     WORKINGDIR=${WORKINGDIR:-/tmp/workingdir.$$}
>     mkdir -p "${WORKINGDIR}"
>     sed -re "s,^(WORKINGDIR=).*,\1${WORKINGDIR},g" /etc/slapt-get/slapt-getrc > "${WORKINGDIR}/slapt-getrc"
>     slapt-get --config "$WORKINGDIR/slapt-getrc" $@
> }
> ```

Does it also need `slapt-get --config "$WORKINGDIR/slapt-getrc" --update`?

**Comment by jaos** [comment]
Yeah, something like

```
slapt-get-customworkdir --update
slapt-get-customworkdir --install ...
# and so on
```
