### ISSUE TITLE
slackbuild problem

### ISSUE THREAD

**Issue by adcdam** [jaos/slapt-get#19]
when running the slackbuild it say line 37:PKG: not assigned variable 
can you supply a slackbuild like in this template for your source? https://slackbuilds.org/templates/meson-template.SlackBuild 
The program compile fine but it doesnt install the compiled files.

**Comment by jaos** [comment]
This was fixed in main with `83ab062a6595ba4d31769681e966a1c6aceabddc`. I'll push a new release.

**Comment by jaos** [comment]
0.11.7 released with the slackbuild fix.

**Comment by adcdam** [comment]
Thanks Jaos, it build fine now.
