### ISSUE TITLE
not a bug but a suggestion

### ISSUE THREAD

**Issue by adcdam** [jaos/slapt-get#20]
Can you add an uncommented Base url to directory with a PACKAGES.TXT and Source for current in /etc/slapt-get/slap-getrc for those who use current? it would be nice if the Slackware current users only have to comment and uncomment a line.

**Comment by jaos** [comment]
Current paths are always s/15.0/current/ on any of the mirrors. The example file in the source tree shows this:
https://github.com/jaos/slapt-get/blob/main/example.slapt-getrc
