### ISSUE TITLE
Got this one. CURLOPT_XFERINFOFUNCTION worked

### ISSUE THREAD

**Issue by antonioleal** [jaos/slapt-get#21]
[8/18] Compiling C object src/libslapt.so.0.11.7.p/slaptcurl.c.o
FAILED: src/libslapt.so.0.11.7.p/slaptcurl.c.o 
ccache cc -Isrc/libslapt.so.0.11.7.p -Isrc -I../src -flto=auto -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -O2 -g '-DPACKAGE="slapt-get"' '-DGETTEXT_PACKAGE="slapt-get"' '-DVERSION="0.11.7"' '-DRC_LOCATION="/etc/slapt-get/slapt-getrc"' '-DRC_DIR="/etc/slapt-get"' -DENABLE_NLS '-DPACKAGE_LOCALE_DIR="/usr/share/locale"' -DSLAPT_HAS_GPGME -ffat-lto-objects -fno-strict-aliasing -Warith-conversion -Warray-bounds=2 -Wcast-align=strict -Wduplicated-cond -Wduplicated-branches -Wformat-nonliteral -Wformat-overflow=2 -Wformat-security -Wformat=2 -Wimplicit-function-declaration -Wimplicit-fallthrough=3 -Wincompatible-pointer-types -Winit-self -Wint-conversion -Wlogical-op -Wmaybe-uninitialized -Wmissing-field-initializers -Wnull-dereference -Wold-style-definition -Wparentheses -Wredundant-decls -Wshadow -Wshift-overflow=2 -Wstrict-overflow -Wstrict-prototypes -Wstringop-overflow=4 -Wswitch-default -Wtrampolines -Wundef -fPIC -MD -MQ src/libslapt.so.0.11.7.p/slaptcurl.c.o -MF src/libslapt.so.0.11.7.p/slaptcurl.c.o.d -o src/libslapt.so.0.11.7.p/slaptcurl.c.o -c ../src/slaptcurl.c
../src/slaptcurl.c: In function ‘slapt_download_data’:
../src/slaptcurl.c:63:13: error: ‘CURLOPT_PROGRESSFUNCTION’ is deprecated: since 7.32.0. Use CURLOPT_XFERINFOFUNCTION [-Werror=deprecated-declarations]
   63 |             curl_easy_setopt(ch, CURLOPT_PROGRESSFUNCTION, slapt_progress_callback);
      |             ^~~~~~~~~~~~~~~~

**Comment by jaos** [comment]
Thanks @antonioleal
