### ISSUE TITLE
Version comparison algorithm behaviour with different tags?

### ISSUE THREAD

**Issue by leoctrl** [jaos/slapt-get#28]
Hi Jason,
In my slapt-getrc I used to have just 2 entries, an official Slackware mirror, and my local repo, i.e.:
SOURCE=https://mirrors.slackware.com/slackware/slackware64-15.0/:OFFICIAL
SOURCE=file:///var/lib/pkgrepo/15.0/x86_64/:CUSTOM

Then I read about a third-party repo called SlackDCE and decided to give it a try, so I added
SOURCE=https://slackdce.radioclub.ar/slackdce/15.0/x86_64/:CUSTOM

After --update, I noticed that slapt-get --upgrade --simulate now suggests to replace some of the packages I built myself and installed from my repo with those from SlackDCE, although Version-Build-Arch are identical, e.g.;

murrine-0.98.2-x86_64-2_SBo is to be upgraded to version 0.98.2-x86_64-2_dce

This seems to contradict FAQ 27, am I doing something wrong, or is the different tags (_SBo vs _dce) that make slapt-get behave that way?
Thanks

**Comment by jaos** [comment]
If you drop the :CUSTOM tag for that package source then it will honor your local custom as a higher priority. That should do what you want. 


Take care,
jason
