### ISSUE TITLE
Reverse dependency to remove unneded packages.

### ISSUE THREAD

**Issue by eleksir** [jaos/slapt-get#3]
Usecase is simple: i installed perl module that bring up about 10-15 other modules as deps. I remove that perl module, but those 10-15 still waste my system. They unused, but still there.

But there is another use case I install some **appA** that uses **libM, libN, libO** as deps, install another **appB** that uses **libN** as dep and separately install **libO** (via `slapt-get --install libO`), because i develop my **appC** and it uses features of **libO**. Then i remove **appA** and want that slapt-get removes also **libM**, but retain **libN**, because it is dep for **appB** and retain **libN** because it was installed not as dep, but as separate app.

**Comment by jaos** [comment]
There is no dependency information stored in the pkgtools information so this would be at best a guess
