### ISSUE TITLE
config files renamed and replaced silently after update

### ISSUE THREAD

**Issue by ghost** [jaos/slapt-get#6]
very annoying

(syslog does no longer output to tty, link to central config file of dnsmasq replaced by file, and so on)

any idea how to stop this?

thx

**Comment by jaos** [comment]
There is no code or logic to do this inside slapt-get. The doinst.sh inside the packages themselves might.

**Comment by jaos** [comment]
Closing since no response. No configuration files are modified. That is up to the package doinst or manual .new configuration file handling.
