### ISSUE TITLE
slapt-get cannot find libcrypto.so.1 in Slackware64 -current.

### ISSUE THREAD

**Issue by Richard-Cranium** [jaos/slapt-get#8]
# slapt-get --version
slapt-get: error while loading shared libraries: libcrypto.so.1: cannot open shared object file: No such file or directory

# ls -l /usr/lib64/libcrypto.*
lrwxrwxrwx 1 root root 16 Aug 26 19:56 /usr/lib64/libcrypto.so -> libcrypto.so.1.1*
lrwxrwxrwx 1 root root 28 Aug 26 19:56 /usr/lib64/libcrypto.so.1.1 -> ../../lib64/libcrypto.so.1.1*

**Comment by jaos** [comment]
Thanks. I'm rebuilding and updating the current packages.
