### ISSUE TITLE
Proper version comparison

### ISSUE THREAD

**Issue by h3xx** [jaos/slapt-get#9]
I've found that when the package installed on the system is `fftw-3.3.10-x86_64-1`, and the requirements for a new package look like this:

    PACKAGE REQUIRED:  fftw >= 3.3.8

Then slapt-get refuses to install the package.

Instead it should probably do proper version comparison so this doesn't happen.

**Comment by jaos** [comment]
It isn't the version comparison. The dependency resolver was refactored it looks like a regression slipped in. Pushed a fix and added a test case.

**Comment by h3xx** [comment]
Works for me now. Thanks! :-)
